/**
 * Round market news — world events that shift emTech Budget / Will costs.
 * AP is never modified (always 1 when action points are on).
 * DOM-free; solo + multiplayer.
 */

import { hashSeed, mulberry32 } from "./economy.js";

/**
 * @typedef {object} MarketNews
 * @property {string} id
 * @property {string} headline
 * @property {string} body
 * @property {string[]} [techIds] — affected tech ids (if set, only these)
 * @property {string[]} [domains] — affected domains (if set and no techIds match path)
 * @property {boolean} [all] — affect every emTech
 * @property {number} budgetDelta — applied to matching techs' Budget (may be negative)
 * @property {number} willDelta — applied to matching techs' Will (may be negative)
 * @property {string} icon — emoji/glyph for UI fallback art
 * @property {"bad"|"good"|"mixed"} tone
 * @property {string} imagePrompt — Imagine prompt used at asset build time
 * @property {string} [image] — static asset path (assets/market-news/{id}.jpg)
 * @property {number} [round] — which round this was rolled for
 * @property {number} [year] — calendar year flavor (optional)
 */

/** Curated bank of world events that reprice emerging tech (122 cards). */
export const MARKET_EVENTS = [
  {
    id: "ram-shortage",
    headline: "RAM shortage hits supply chains",
    body: "Memory chips are scarce and pricey. Computing projects need deeper pockets before they leave the lab.",
    techIds: ["computing"],
    budgetDelta: 1,
    willDelta: 0,
    icon: "💾",
    tone: "bad",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: RAM shortage hits supply chains. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/ram-shortage.jpg",
  },
  {
    id: "ai-datacenter-backlash",
    headline: "Public divided over AI data centers",
    body: "People don't want a data center built in their state. Fielding AI and heavy compute needs more political will.",
    techIds: ["ai", "computing"],
    budgetDelta: 0,
    willDelta: 2,
    icon: "🏙️",
    tone: "bad",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Public divided over AI data centers. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/ai-datacenter-backlash.jpg",
  },
  {
    id: "solar-glut",
    headline: "Solar panel glut drops prices",
    body: "Factories overbuilt. Solar and battery kits flood municipal catalogs — capital costs ease.",
    techIds: ["solar", "battery"],
    budgetDelta: -1,
    willDelta: 0,
    icon: "☀",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Solar panel glut drops prices. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/solar-glut.jpg",
  },
  {
    id: "nuclear-permit-wave",
    headline: "Nuclear permits move faster",
    body: "A regional compact streamlines small-reactor reviews. Political will for nuclear ticks up.",
    techIds: ["nuclear"],
    budgetDelta: 0,
    willDelta: -1,
    icon: "☢",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Nuclear permits move faster. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/nuclear-permit-wave.jpg",
  },
  {
    id: "drone-airspace-clamp",
    headline: "Drone airspace rules tighten",
    body: "New corridors and insurance mandates raise the bar. Autonomy projects need budget and buy-in.",
    techIds: ["drones", "self-driving"],
    budgetDelta: 1,
    willDelta: 1,
    icon: "🛸",
    tone: "bad",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Drone airspace rules tighten. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/drone-airspace-clamp.jpg",
  },
  {
    id: "gene-sequencing-boom",
    headline: "Portable sequencers get cheaper",
    body: "A price war in field genomics. Pathogen and biotech stacks cost less capital to stand up.",
    techIds: ["gene-sequencing", "synbio", "genetic-engineering"],
    budgetDelta: -1,
    willDelta: 0,
    icon: "🧬",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Portable sequencers get cheaper. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/gene-sequencing-boom.jpg",
  },
  {
    id: "biotech-scare",
    headline: "Lab-leak scare fans biotech fear",
    body: "Headlines outrun evidence. Synthetic biology and genetic work face a tougher political climate.",
    techIds: ["synbio", "genetic-engineering", "gene-sequencing"],
    budgetDelta: 0,
    willDelta: 2,
    icon: "⚠️",
    tone: "bad",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Lab-leak scare fans biotech fear. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/biotech-scare.jpg",
  },
  {
    id: "grid-congestion",
    headline: "Grid congestion fees spike",
    body: "Transmission bottlenecks make energy projects pricier to wire up — especially large generation.",
    techIds: ["energy", "wind", "solar", "geothermal", "tidal", "wave"],
    budgetDelta: 1,
    willDelta: 0,
    icon: "⚡",
    tone: "bad",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Grid congestion fees spike. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/grid-congestion.jpg",
  },
  {
    id: "open-source-models",
    headline: "Open-source models flood the market",
    body: "Capable free weights lower the barrier. AI assistants get cheaper to stand up locally.",
    techIds: ["ai"],
    budgetDelta: -1,
    willDelta: 0,
    icon: "✦",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Open-source models flood the market. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/open-source-models.jpg",
  },
  {
    id: "robot-labor-pushback",
    headline: "Unions push back on care robots",
    body: "Care and logistics automation meets organized resistance. Political will is the scarce resource.",
    techIds: ["robots"],
    budgetDelta: 0,
    willDelta: 1,
    icon: "🤖",
    tone: "bad",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Unions push back on care robots. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/robot-labor-pushback.jpg",
  },
  {
    id: "chip-export-thaw",
    headline: "Export controls ease on edge chips",
    body: "A temporary thaw. Edge computing and IoT kits drop in price for civic projects.",
    techIds: ["computing", "iot", "networks"],
    budgetDelta: -1,
    willDelta: 0,
    icon: "📡",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Export controls ease on edge chips. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/chip-export-thaw.jpg",
  },
  {
    id: "privacy-backlash",
    headline: "Sensor surveillance backlash",
    body: "Communities reject always-on cameras and meters. IoT and networks need more political cover.",
    techIds: ["iot", "networks", "ai"],
    budgetDelta: 0,
    willDelta: 1,
    icon: "👁",
    tone: "bad",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Sensor surveillance backlash. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/privacy-backlash.jpg",
  },
  {
    id: "print-shop-grants",
    headline: "Municipal 3D print grants land",
    body: "Cities fund local fab shops. Additive manufacturing and materials get a capital break.",
    techIds: ["print3d", "materials"],
    budgetDelta: -1,
    willDelta: 0,
    icon: "🖨",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Municipal 3D print grants land. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/print-shop-grants.jpg",
  },
  {
    id: "rare-earth-squeeze",
    headline: "Rare-earth squeeze hits hardware",
    body: "Magnets, batteries, and advanced materials cost more. Hardware-heavy stacks feel it.",
    domains: ["power", "portal"],
    budgetDelta: 1,
    willDelta: 0,
    icon: "⛏",
    tone: "bad",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Rare-earth squeeze hits hardware. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/rare-earth-squeeze.jpg",
  },
  {
    id: "climate-fund-surge",
    headline: "Adaptation funds open early",
    body: "A climate window funds local resilience tech. Political will for green stacks softens.",
    domains: ["power", "portal"],
    budgetDelta: 0,
    willDelta: -1,
    icon: "🌍",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Adaptation funds open early. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/climate-fund-surge.jpg",
  },
  {
    id: "vr-training-fad",
    headline: "VR training budgets cut",
    body: "Enterprises walk back headset programs. Link-domain projects need more capital to justify.",
    domains: ["link"],
    budgetDelta: 1,
    willDelta: 0,
    icon: "🕶",
    tone: "bad",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: VR training budgets cut. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/vr-training-fad.jpg",
  },
  {
    id: "quantum-hype-cycle",
    headline: "Quantum hype cools — pilots pause",
    body: "Investors wait for clearer niches. Quantum work needs more will to keep sponsors interested.",
    techIds: ["quantum", "quantum-internet"],
    budgetDelta: 0,
    willDelta: 1,
    icon: "⚛",
    tone: "mixed",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Quantum hype cools — pilots pause. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/quantum-hype-cycle.jpg",
  },
  {
    id: "community-broadband",
    headline: "Community broadband wins a vote",
    body: "Fiber co-ops pass. Networks and coordination tools face less political friction.",
    techIds: ["networks", "iot"],
    budgetDelta: 0,
    willDelta: -1,
    icon: "⛓",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Community broadband wins a vote. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/community-broadband.jpg",
  },
  {
    id: "crypto-winter-thaw",
    headline: "Ledger tools rebrand as civic rails",
    body: "Less hype, more procurement. Crypto-style ledgers cost a little less political capital.",
    techIds: ["crypto"],
    budgetDelta: 0,
    willDelta: -1,
    icon: "Ƀ",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Ledger tools rebrand as civic rails. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/crypto-winter-thaw.jpg",
  },
  {
    id: "battery-fire-scare",
    headline: "Warehouse battery fire dominates news",
    body: "Safety fears raise insurance and compliance costs for battery projects.",
    techIds: ["battery"],
    budgetDelta: 1,
    willDelta: 1,
    icon: "🔋",
    tone: "bad",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Warehouse battery fire dominates news. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/battery-fire-scare.jpg",
  },
  {
    id: "wind-siting-wars",
    headline: "Wind siting wars escalate",
    body: "Coastal and ridge communities fight new turbines. Wind projects need more political will.",
    techIds: ["wind"],
    budgetDelta: 0,
    willDelta: 1,
    icon: "🌬",
    tone: "bad",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Wind siting wars escalate. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/wind-siting-wars.jpg",
  },
  {
    id: "offshore-wind-subsidy",
    headline: "Offshore wind subsidy package",
    body: "A regional package underwrites marine wind. Capital costs ease for wind stacks.",
    techIds: ["wind", "energy"],
    budgetDelta: -1,
    willDelta: 0,
    icon: "🌊",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Offshore wind subsidy package. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/offshore-wind-subsidy.jpg",
  },
  {
    id: "geothermal-drill-boom",
    headline: "Geothermal drill costs drop",
    body: "New drill bits and shared rigs cut baseload heat projects. Geothermal gets cheaper to start.",
    techIds: ["geothermal"],
    budgetDelta: -1,
    willDelta: 0,
    icon: "🌋",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Geothermal drill costs drop. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/geothermal-drill-boom.jpg",
  },
  {
    id: "seismic-permit-freeze",
    headline: "Seismic fears freeze geothermal permits",
    body: "Induced-quake stories stall local permits. Geothermal needs more political cover.",
    techIds: ["geothermal"],
    budgetDelta: 0,
    willDelta: 1,
    icon: "📉",
    tone: "bad",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Seismic fears freeze geothermal permits. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/seismic-permit-freeze.jpg",
  },
  {
    id: "tidal-pilot-success",
    headline: "Tidal pilot beats forecasts",
    body: "A harbor pilot posts reliable output. Tidal and wave tech look more fundable.",
    techIds: ["tidal", "wave"],
    budgetDelta: -1,
    willDelta: 0,
    icon: "🌙",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Tidal pilot beats forecasts. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/tidal-pilot-success.jpg",
  },
  {
    id: "marine-storm-damage",
    headline: "Storm damages marine energy kit",
    body: "Insurance after a bad season raises capital for tidal and wave projects.",
    techIds: ["tidal", "wave"],
    budgetDelta: 1,
    willDelta: 0,
    icon: "🌪",
    tone: "bad",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Storm damages marine energy kit. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/marine-storm-damage.jpg",
  },
  {
    id: "nuclear-waste-standoff",
    headline: "Nuclear waste standoff returns",
    body: "Storage politics flare. Nuclear needs more will even where reactors are welcome on paper.",
    techIds: ["nuclear"],
    budgetDelta: 0,
    willDelta: 1,
    icon: "☢",
    tone: "bad",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Nuclear waste standoff returns. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/nuclear-waste-standoff.jpg",
  },
  {
    id: "smr-factory-discount",
    headline: "SMR factory offers bulk pricing",
    body: "Modular reactor vendors cut first-unit premiums. Nuclear capital eases slightly.",
    techIds: ["nuclear"],
    budgetDelta: -1,
    willDelta: 0,
    icon: "🏭",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: SMR factory offers bulk pricing. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/smr-factory-discount.jpg",
  },
  {
    id: "oil-price-spike",
    headline: "Oil price spike revives electrify-now",
    body: "Fossil volatility makes clean power stacks easier to sell politically.",
    techIds: ["solar", "wind", "battery", "energy"],
    budgetDelta: 0,
    willDelta: -1,
    icon: "🛢",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Oil price spike revives electrify-now. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/oil-price-spike.jpg",
  },
  {
    id: "gas-lobby-blitz",
    headline: "Gas lobby blitz hits clean power",
    body: "Incumbent messaging slows clean generation. Will costs rise for power techs.",
    domains: ["power"],
    budgetDelta: 0,
    willDelta: 1,
    icon: "📢",
    tone: "bad",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Gas lobby blitz hits clean power. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/gas-lobby-blitz.jpg",
  },
  {
    id: "microgrid-standard",
    headline: "Microgrid standard adopted",
    body: "A shared standard cuts integration cost for energy, battery, and networks stacks.",
    techIds: ["energy", "battery", "networks", "iot"],
    budgetDelta: -1,
    willDelta: 0,
    icon: "🔌",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Microgrid standard adopted. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/microgrid-standard.jpg",
  },
  {
    id: "utility-monopoly-fee",
    headline: "Utility monopoly fees for edge devices",
    body: "Distribution charges hit local generation and storage. Power hardware costs more.",
    techIds: ["solar", "battery", "energy"],
    budgetDelta: 1,
    willDelta: 0,
    icon: "💸",
    tone: "bad",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Utility monopoly fees for edge devices. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/utility-monopoly-fee.jpg",
  },
  {
    id: "copper-shortage",
    headline: "Copper shortage hits wiring",
    body: "Cables and motors get pricey. Energy and mover hardware budgets climb.",
    techIds: ["energy", "transportation", "self-driving", "robots"],
    budgetDelta: 1,
    willDelta: 0,
    icon: "🟧",
    tone: "bad",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Copper shortage hits wiring. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/copper-shortage.jpg",
  },
  {
    id: "lithium-price-crash",
    headline: "Lithium price crash",
    body: "Battery packs get cheaper again after a supply glut.",
    techIds: ["battery", "self-driving", "drones"],
    budgetDelta: -1,
    willDelta: 0,
    icon: "📉",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Lithium price crash. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/lithium-price-crash.jpg",
  },
  {
    id: "hydrogen-hype-tax",
    headline: "Hydrogen hype tax on energy budgets",
    body: "Policymakers divert funds to unready H2 schemes. Local power pilots pay more to compete.",
    techIds: ["energy", "solar", "wind"],
    budgetDelta: 1,
    willDelta: 0,
    icon: "💨",
    tone: "bad",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Hydrogen hype tax on energy budgets. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/hydrogen-hype-tax.jpg",
  },
  {
    id: "community-solar-law",
    headline: "Community solar law passes",
    body: "Shared solar co-ops get easy rules. Solar will cost drops.",
    techIds: ["solar"],
    budgetDelta: 0,
    willDelta: -1,
    icon: "☀",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Community solar law passes. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/community-solar-law.jpg",
  },
  {
    id: "night-storage-mandate",
    headline: "Night storage mandate",
    body: "New rules couple generation with storage. Battery capital rises; solar politics ease a bit.",
    techIds: ["battery", "solar"],
    budgetDelta: 1,
    willDelta: -1,
    icon: "🌙",
    tone: "mixed",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Night storage mandate. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/night-storage-mandate.jpg",
  },
  {
    id: "blackout-week",
    headline: "Blackout week focuses minds",
    body: "After multi-day outages, political will for local energy and batteries rises.",
    techIds: ["energy", "battery", "solar", "wind"],
    budgetDelta: 0,
    willDelta: -1,
    icon: "🌑",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Blackout week focuses minds. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/blackout-week.jpg",
  },
  {
    id: "ai-chip-tax",
    headline: "AI chip import tax",
    body: "Specialized accelerators get pricier. AI and computing stacks need more capital.",
    techIds: ["ai", "computing"],
    budgetDelta: 1,
    willDelta: 0,
    icon: "🧾",
    tone: "bad",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: AI chip import tax. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/ai-chip-tax.jpg",
  },
  {
    id: "teacher-ai-grants",
    headline: "Teacher AI copilot grants",
    body: "Education funds underwrite classroom AI. Will and capital ease for AI projects.",
    techIds: ["ai"],
    budgetDelta: -1,
    willDelta: -1,
    icon: "📚",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Teacher AI copilot grants. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/teacher-ai-grants.jpg",
  },
  {
    id: "deepfake-scandal",
    headline: "Deepfake scandal week",
    body: "Trust crashes. AI projects need more political will to clear scrutiny.",
    techIds: ["ai"],
    budgetDelta: 0,
    willDelta: 2,
    icon: "🎭",
    tone: "bad",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Deepfake scandal week. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/deepfake-scandal.jpg",
  },
  {
    id: "robot-lease-deals",
    headline: "Robot-as-a-service lease deals",
    body: "Vendors finance bodies monthly. Robots cost less upfront capital.",
    techIds: ["robots"],
    budgetDelta: -1,
    willDelta: 0,
    icon: "🤝",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Robot-as-a-service lease deals. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/robot-lease-deals.jpg",
  },
  {
    id: "robot-injury-lawsuit",
    headline: "Robot injury lawsuit goes viral",
    body: "Liability fears raise compliance spend for robots.",
    techIds: ["robots"],
    budgetDelta: 1,
    willDelta: 1,
    icon: "⚖️",
    tone: "bad",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Robot injury lawsuit goes viral. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/robot-injury-lawsuit.jpg",
  },
  {
    id: "warehouse-robot-boom",
    headline: "Warehouse robot boom discounts spares",
    body: "Overbuilt logistics robots spill into civic markets cheaper.",
    techIds: ["robots", "drones"],
    budgetDelta: -1,
    willDelta: 0,
    icon: "📦",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Warehouse robot boom discounts spares. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/warehouse-robot-boom.jpg",
  },
  {
    id: "ai-energy-backlash",
    headline: "AI energy use backlash",
    body: "Communities link AI to power strain. AI will cost rises.",
    techIds: ["ai"],
    budgetDelta: 0,
    willDelta: 1,
    icon: "🔥",
    tone: "bad",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: AI energy use backlash. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/ai-energy-backlash.jpg",
  },
  {
    id: "open-robotics-kit",
    headline: "Open robotics kit hits shelves",
    body: "Shared designs and parts drop robot build costs.",
    techIds: ["robots", "print3d"],
    budgetDelta: -1,
    willDelta: 0,
    icon: "🧰",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Open robotics kit hits shelves. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/open-robotics-kit.jpg",
  },
  {
    id: "automation-tax-talk",
    headline: "Automation tax talk returns",
    body: "Politicians float robot taxes. Automator stacks need more will.",
    domains: ["automator"],
    budgetDelta: 0,
    willDelta: 1,
    icon: "🏛",
    tone: "bad",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Automation tax talk returns. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/automation-tax-talk.jpg",
  },
  {
    id: "ai-safety-fund",
    headline: "National AI safety fund",
    body: "Compliance and eval tools get subsidies. AI capital eases if you play by the book.",
    techIds: ["ai"],
    budgetDelta: -1,
    willDelta: 0,
    icon: "🛡",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: National AI safety fund. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/ai-safety-fund.jpg",
  },
  {
    id: "ev-charger-glut",
    headline: "EV charger glut",
    body: "Charge hardware is cheap. Transportation and self-driving support costs fall.",
    techIds: ["transportation", "self-driving", "battery"],
    budgetDelta: -1,
    willDelta: 0,
    icon: "🔌",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: EV charger glut. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/ev-charger-glut.jpg",
  },
  {
    id: "road-pricing-fight",
    headline: "Road pricing fight",
    body: "Congestion charges spark protests. Self-driving and transport need more will.",
    techIds: ["self-driving", "transportation"],
    budgetDelta: 0,
    willDelta: 1,
    icon: "🛣",
    tone: "bad",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Road pricing fight. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/road-pricing-fight.jpg",
  },
  {
    id: "autonomy-corridor-opens",
    headline: "Autonomy corridor opens",
    body: "A city opens a mapped shuttle corridor. Self-driving capital and will ease.",
    techIds: ["self-driving", "networks"],
    budgetDelta: -1,
    willDelta: -1,
    icon: "🚌",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Autonomy corridor opens. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/autonomy-corridor-opens.jpg",
  },
  {
    id: "drone-crash-ban",
    headline: "Drone crash triggers temporary ban",
    body: "A high-profile incident grounds local drones until rules tighten.",
    techIds: ["drones"],
    budgetDelta: 1,
    willDelta: 1,
    icon: "🚫",
    tone: "bad",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Drone crash triggers temporary ban. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/drone-crash-ban.jpg",
  },
  {
    id: "medical-drone-lane",
    headline: "Medical drone lane approved",
    body: "Blood and vaccine corridors get permanent status. Drones get easier politically.",
    techIds: ["drones"],
    budgetDelta: 0,
    willDelta: -1,
    icon: "🩸",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Medical drone lane approved. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/medical-drone-lane.jpg",
  },
  {
    id: "satellite-bandwidth-sale",
    headline: "Satellite bandwidth sale",
    body: "Space connectivity vendors dump capacity. Space and networks get cheaper to wire.",
    techIds: ["space", "networks"],
    budgetDelta: -1,
    willDelta: 0,
    icon: "🛰",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Satellite bandwidth sale. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/satellite-bandwidth-sale.jpg",
  },
  {
    id: "space-debris-scare",
    headline: "Space debris scare",
    body: "Launch insurance spikes. Space projects need more capital.",
    techIds: ["space"],
    budgetDelta: 1,
    willDelta: 0,
    icon: "☄",
    tone: "bad",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Space debris scare. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/space-debris-scare.jpg",
  },
  {
    id: "fiber-cut-wave",
    headline: "Fiber cut crime wave",
    body: "Cable theft raises network resilience costs.",
    techIds: ["networks"],
    budgetDelta: 1,
    willDelta: 0,
    icon: "✂️",
    tone: "bad",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Fiber cut crime wave. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/fiber-cut-wave.jpg",
  },
  {
    id: "mesh-radio-legalized",
    headline: "Mesh radio legalized",
    body: "Community mesh networks get clear spectrum rules. Networks and IoT will ease.",
    techIds: ["networks", "iot"],
    budgetDelta: 0,
    willDelta: -1,
    icon: "📻",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Mesh radio legalized. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/mesh-radio-legalized.jpg",
  },
  {
    id: "quantum-link-pilot",
    headline: "Quantum link pilot funded",
    body: "A research corridor funds quantum networking trials. Quantum internet capital eases.",
    techIds: ["quantum-internet", "quantum"],
    budgetDelta: -1,
    willDelta: 0,
    icon: "🔗",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Quantum link pilot funded. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/quantum-link-pilot.jpg",
  },
  {
    id: "transport-strike",
    headline: "Transport strike disrupts pilots",
    body: "Labor action freezes mobility trials. Mover stacks need more will.",
    domains: ["mover"],
    budgetDelta: 0,
    willDelta: 1,
    icon: "🪧",
    tone: "bad",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Transport strike disrupts pilots. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/transport-strike.jpg",
  },
  {
    id: "bike-lane-data-deal",
    headline: "Bike-lane sensor deal",
    body: "Cities bulk-buy IoT for mobility. Networks and IoT hardware get cheaper.",
    techIds: ["iot", "networks", "transportation"],
    budgetDelta: -1,
    willDelta: 0,
    icon: "🚲",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Bike-lane sensor deal. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/bike-lane-data-deal.jpg",
  },
  {
    id: "lidar-price-war",
    headline: "Lidar price war",
    body: "Sensors for autonomy and drones get cheaper.",
    techIds: ["self-driving", "drones", "robots"],
    budgetDelta: -1,
    willDelta: 0,
    icon: "📡",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Lidar price war. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/lidar-price-war.jpg",
  },
  {
    id: "gps-jamming-zone",
    headline: "GPS jamming zone expands",
    body: "Navigation risk raises cost for drones, space, and self-driving ops.",
    techIds: ["drones", "self-driving", "space"],
    budgetDelta: 1,
    willDelta: 0,
    icon: "📍",
    tone: "bad",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: GPS jamming zone expands. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/gps-jamming-zone.jpg",
  },
  {
    id: "gene-therapy-approval",
    headline: "Gene therapy approval wave",
    body: "Regulators clear more therapies. Genetic engineering will eases.",
    techIds: ["genetic-engineering", "synbio"],
    budgetDelta: 0,
    willDelta: -1,
    icon: "✅",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Gene therapy approval wave. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/gene-therapy-approval.jpg",
  },
  {
    id: "clinic-sequencer-rebate",
    headline: "Clinic sequencer rebate",
    body: "Public health rebates portable sequencing kits.",
    techIds: ["gene-sequencing"],
    budgetDelta: -1,
    willDelta: 0,
    icon: "🏥",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Clinic sequencer rebate. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/clinic-sequencer-rebate.jpg",
  },
  {
    id: "gmo-crop-ban-talk",
    headline: "GMO crop ban talk spreads",
    body: "Farm politics harden. Synbio and genetic engineering need more will.",
    techIds: ["synbio", "genetic-engineering", "alt-proteins"],
    budgetDelta: 0,
    willDelta: 1,
    icon: "🌾",
    tone: "bad",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: GMO crop ban talk spreads. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/gmo-crop-ban-talk.jpg",
  },
  {
    id: "alt-protein-price-parity",
    headline: "Alt-protein price parity",
    body: "Plant and fermentation proteins hit cost parity in more cafeterias.",
    techIds: ["alt-proteins"],
    budgetDelta: -1,
    willDelta: -1,
    icon: "🥗",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Alt-protein price parity. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/alt-protein-price-parity.jpg",
  },
  {
    id: "cultured-meat-ban",
    headline: "Cultured meat ban in key market",
    body: "A ban raises political cost for alternative proteins.",
    techIds: ["alt-proteins", "synbio"],
    budgetDelta: 0,
    willDelta: 2,
    icon: "🚫",
    tone: "bad",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Cultured meat ban in key market. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/cultured-meat-ban.jpg",
  },
  {
    id: "bci-trial-success",
    headline: "BCI trial restores speech",
    body: "Positive trial coverage lowers political friction for brain-computer interfaces.",
    techIds: ["bci"],
    budgetDelta: 0,
    willDelta: -1,
    icon: "🧠",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: BCI trial restores speech. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/bci-trial-success.jpg",
  },
  {
    id: "bci-ethics-probe",
    headline: "BCI ethics probe opens",
    body: "Consent and data fears raise will cost for neural interfaces.",
    techIds: ["bci"],
    budgetDelta: 0,
    willDelta: 1,
    icon: "🔍",
    tone: "bad",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: BCI ethics probe opens. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/bci-ethics-probe.jpg",
  },
  {
    id: "pandemic-stockpile",
    headline: "Pandemic stockpile restock",
    body: "Public buyers bulk-order diagnostics. Gene sequencing capital eases.",
    techIds: ["gene-sequencing", "synbio"],
    budgetDelta: -1,
    willDelta: 0,
    icon: "🧪",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Pandemic stockpile restock. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/pandemic-stockpile.jpg",
  },
  {
    id: "synbio-ip-thicket",
    headline: "Synbio IP thicket",
    body: "Licensing fights raise capital for synthetic biology builds.",
    techIds: ["synbio"],
    budgetDelta: 1,
    willDelta: 0,
    icon: "📄",
    tone: "bad",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Synbio IP thicket. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/synbio-ip-thicket.jpg",
  },
  {
    id: "crispr-tool-drop",
    headline: "CRISPR tool prices drop",
    body: "Gene-editing reagents get cheaper for local labs.",
    techIds: ["genetic-engineering", "synbio"],
    budgetDelta: -1,
    willDelta: 0,
    icon: "✂",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: CRISPR tool prices drop. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/crispr-tool-drop.jpg",
  },
  {
    id: "blood-sample-privacy",
    headline: "Blood sample privacy law",
    body: "Biobank rules tighten. Sequencing and BCI projects need more will.",
    techIds: ["gene-sequencing", "bci"],
    budgetDelta: 0,
    willDelta: 1,
    icon: "🩸",
    tone: "bad",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Blood sample privacy law. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/blood-sample-privacy.jpg",
  },
  {
    id: "school-lunch-proteins",
    headline: "School lunch protein pilots",
    body: "Public kitchens trial alt proteins — political path opens.",
    techIds: ["alt-proteins"],
    budgetDelta: 0,
    willDelta: -1,
    icon: "🍎",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: School lunch protein pilots. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/school-lunch-proteins.jpg",
  },
  {
    id: "vr-headset-clearance",
    headline: "VR headset clearance sale",
    body: "Enterprise returns flood the market. VR capital drops.",
    techIds: ["vr"],
    budgetDelta: -1,
    willDelta: 0,
    icon: "🕶",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: VR headset clearance sale. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/vr-headset-clearance.jpg",
  },
  {
    id: "ar-workplace-mandate",
    headline: "AR workplace safety mandate",
    body: "Factories fund AR training — Link domain will eases.",
    domains: ["link"],
    budgetDelta: 0,
    willDelta: -1,
    icon: "🦺",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: AR workplace safety mandate. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/ar-workplace-mandate.jpg",
  },
  {
    id: "motion-sickness-report",
    headline: "Motion sickness report goes viral",
    body: "VR adoption politics worsen for a season.",
    techIds: ["vr"],
    budgetDelta: 0,
    willDelta: 1,
    icon: "🤢",
    tone: "bad",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Motion sickness report goes viral. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/motion-sickness-report.jpg",
  },
  {
    id: "metaverse-budget-purge",
    headline: "Metaverse budget purge",
    body: "Big tech cuts hurt headset supply chains; short-term prices spike.",
    techIds: ["vr"],
    budgetDelta: 1,
    willDelta: 0,
    icon: "🧹",
    tone: "bad",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Metaverse budget purge. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/metaverse-budget-purge.jpg",
  },
  {
    id: "medical-vr-therapy",
    headline: "Medical VR therapy covered",
    body: "Insurers reimburse VR therapy modules. Will and capital ease.",
    techIds: ["vr"],
    budgetDelta: -1,
    willDelta: -1,
    icon: "🩺",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Medical VR therapy covered. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/medical-vr-therapy.jpg",
  },
  {
    id: "iot-chip-shortage",
    headline: "IoT chip shortage returns",
    body: "Sensor nodes get pricier for civic builds.",
    techIds: ["iot"],
    budgetDelta: 1,
    willDelta: 0,
    icon: "📟",
    tone: "bad",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: IoT chip shortage returns. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/iot-chip-shortage.jpg",
  },
  {
    id: "smart-city-grant",
    headline: "Smart city sensor grant",
    body: "A federal program funds IoT for water, air, and flood meters.",
    techIds: ["iot", "networks"],
    budgetDelta: -1,
    willDelta: -1,
    icon: "🏙",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Smart city sensor grant. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/smart-city-grant.jpg",
  },
  {
    id: "nano-hype-funding",
    headline: "Nano materials hype funding",
    body: "A materials sprint drops nano and advanced materials capital.",
    techIds: ["nano", "materials"],
    budgetDelta: -1,
    willDelta: 0,
    icon: "🔬",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Nano materials hype funding. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/nano-hype-funding.jpg",
  },
  {
    id: "nano-toxicity-study",
    headline: "Nano toxicity study alarms public",
    body: "Safety reviews raise will cost for nano projects.",
    techIds: ["nano"],
    budgetDelta: 0,
    willDelta: 1,
    icon: "⚠",
    tone: "bad",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Nano toxicity study alarms public. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/nano-toxicity-study.jpg",
  },
  {
    id: "recycled-filaments",
    headline: "Recycled 3D filaments flood market",
    body: "Print feedstock gets cheaper for local fab.",
    techIds: ["print3d", "materials"],
    budgetDelta: -1,
    willDelta: 0,
    icon: "♻️",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Recycled 3D filaments flood market. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/recycled-filaments.jpg",
  },
  {
    id: "printer-fire-recall",
    headline: "3D printer fire recall",
    body: "Insurance and compliance raise print3d capital.",
    techIds: ["print3d"],
    budgetDelta: 1,
    willDelta: 1,
    icon: "🔥",
    tone: "bad",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: 3D printer fire recall. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/printer-fire-recall.jpg",
  },
  {
    id: "materials-tariff",
    headline: "Advanced materials tariff",
    body: "Import duties hit specialty materials and nano feedstocks.",
    techIds: ["materials", "nano"],
    budgetDelta: 1,
    willDelta: 0,
    icon: "🚢",
    tone: "bad",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Advanced materials tariff. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/materials-tariff.jpg",
  },
  {
    id: "open-hardware-license",
    headline: "Open hardware license wave",
    body: "Shared designs cut materials and print3d project capital.",
    techIds: ["print3d", "materials", "iot"],
    budgetDelta: -1,
    willDelta: 0,
    icon: "🔓",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Open hardware license wave. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/open-hardware-license.jpg",
  },
  {
    id: "right-to-repair-win",
    headline: "Right-to-repair win",
    body: "Local repair laws favor maintainable IoT and print stacks.",
    techIds: ["iot", "print3d", "robots"],
    budgetDelta: 0,
    willDelta: -1,
    icon: "🔧",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Right-to-repair win. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/right-to-repair-win.jpg",
  },
  {
    id: "e-waste-crackdown",
    headline: "E-waste crackdown",
    body: "Disposal fees raise capital for hardware-heavy portal stacks.",
    domains: ["portal"],
    budgetDelta: 1,
    willDelta: 0,
    icon: "🗑",
    tone: "bad",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: E-waste crackdown. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/e-waste-crackdown.jpg",
  },
  {
    id: "interest-rate-hike",
    headline: "Interest rate hike",
    body: "Capital markets tighten. Almost every hardware stack costs more to fund.",
    all: true,
    budgetDelta: 1,
    willDelta: 0,
    icon: "📈",
    tone: "bad",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Interest rate hike. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/interest-rate-hike.jpg",
  },
  {
    id: "stimulus-tech-window",
    headline: "Stimulus tech window",
    body: "A short spending window softens capital for local tech pilots.",
    all: true,
    budgetDelta: -1,
    willDelta: 0,
    icon: "🪟",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Stimulus tech window. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/stimulus-tech-window.jpg",
  },
  {
    id: "election-year-caution",
    headline: "Election-year caution",
    body: "Officials avoid controversial tech. Will rises across frontier stacks.",
    domains: ["automator", "lifeforce", "link"],
    budgetDelta: 0,
    willDelta: 1,
    icon: "🗳",
    tone: "bad",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Election-year caution. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/election-year-caution.jpg",
  },
  {
    id: "mayors-innovation-pact",
    headline: "Mayors innovation pact",
    body: "Cities share procurement templates. Political will eases for multi-domain pilots.",
    all: true,
    budgetDelta: 0,
    willDelta: -1,
    icon: "🤝",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Mayors innovation pact. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/mayors-innovation-pact.jpg",
  },
  {
    id: "cyberattack-week",
    headline: "Cyberattack week",
    body: "Security mandates raise costs for networks, IoT, AI, and crypto.",
    techIds: ["networks", "iot", "ai", "crypto"],
    budgetDelta: 1,
    willDelta: 1,
    icon: "🛡",
    tone: "bad",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Cyberattack week. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/cyberattack-week.jpg",
  },
  {
    id: "open-data-law",
    headline: "Open data law passes",
    body: "Cities publish APIs. Networks and IoT projects face less political friction.",
    techIds: ["networks", "iot", "ai"],
    budgetDelta: 0,
    willDelta: -1,
    icon: "🗂",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Open data law passes. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/open-data-law.jpg",
  },
  {
    id: "talent-visa-freeze",
    headline: "Talent visa freeze",
    body: "Skilled labor shortages raise costs for computing, AI, and quantum.",
    techIds: ["computing", "ai", "quantum"],
    budgetDelta: 1,
    willDelta: 0,
    icon: "🛂",
    tone: "bad",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Talent visa freeze. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/talent-visa-freeze.jpg",
  },
  {
    id: "university-lab-share",
    headline: "University lab share program",
    body: "Shared equipment lowers capital for gene, quantum, and materials work.",
    techIds: ["gene-sequencing", "quantum", "materials", "synbio"],
    budgetDelta: -1,
    willDelta: 0,
    icon: "🎓",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: University lab share program. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/university-lab-share.jpg",
  },
  {
    id: "insurance-premium-spike",
    headline: "Tech pilot insurance spike",
    body: "Underwriters raise premiums on drones, robots, and nuclear-adjacent work.",
    techIds: ["drones", "robots", "nuclear", "battery"],
    budgetDelta: 1,
    willDelta: 0,
    icon: "📋",
    tone: "bad",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Tech pilot insurance spike. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/insurance-premium-spike.jpg",
  },
  {
    id: "philanthropy-sprint",
    headline: "Philanthropy sprint for local tech",
    body: "Foundations match municipal invent funds. Capital eases across the board.",
    all: true,
    budgetDelta: -1,
    willDelta: 0,
    icon: "💝",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Philanthropy sprint for local tech. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/philanthropy-sprint.jpg",
  },
  {
    id: "disinfo-wave",
    headline: "Disinfo wave about tech pilots",
    body: "Rumors force extra community process. Will rises for visible stacks.",
    domains: ["automator", "mover", "lifeforce"],
    budgetDelta: 0,
    willDelta: 1,
    icon: "💬",
    tone: "bad",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Disinfo wave about tech pilots. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/disinfo-wave.jpg",
  },
  {
    id: "youth-climate-march",
    headline: "Youth climate march",
    body: "Street pressure softens will for clean power and materials stacks.",
    domains: ["power", "portal"],
    budgetDelta: 0,
    willDelta: -1,
    icon: "✊",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Youth climate march. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/youth-climate-march.jpg",
  },
  {
    id: "crypto-crash",
    headline: "Crypto crash",
    body: "Speculative heat dies; remaining civic ledger work needs less will, more careful capital.",
    techIds: ["crypto"],
    budgetDelta: 1,
    willDelta: -1,
    icon: "📉",
    tone: "mixed",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Crypto crash. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/crypto-crash.jpg",
  },
  {
    id: "stablecoin-payroll",
    headline: "Stablecoin payroll pilots",
    body: "Cities trial transparent local funds. Crypto capital eases slightly.",
    techIds: ["crypto", "networks"],
    budgetDelta: -1,
    willDelta: 0,
    icon: "💰",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Stablecoin payroll pilots. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/stablecoin-payroll.jpg",
  },
  {
    id: "bci-data-breach",
    headline: "BCI vendor data breach",
    body: "Neural data fears spike will cost for BCI.",
    techIds: ["bci"],
    budgetDelta: 0,
    willDelta: 2,
    icon: "🔓",
    tone: "bad",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: BCI vendor data breach. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/bci-data-breach.jpg",
  },
  {
    id: "space-earth-obs-deal",
    headline: "Earth observation deal for towns",
    body: "Cheap satellite data feeds local planning. Space and AI capital ease.",
    techIds: ["space", "ai", "networks"],
    budgetDelta: -1,
    willDelta: 0,
    icon: "🌎",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Earth observation deal for towns. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/space-earth-obs-deal.jpg",
  },
  {
    id: "self-driving-pedestrian-incident",
    headline: "Self-driving pedestrian incident",
    body: "A high-profile crash freezes will for autonomy.",
    techIds: ["self-driving"],
    budgetDelta: 0,
    willDelta: 2,
    icon: "🚨",
    tone: "bad",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Self-driving pedestrian incident. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/self-driving-pedestrian-incident.jpg",
  },
  {
    id: "drone-delivery-holiday",
    headline: "Drone delivery holiday rush",
    body: "Seasonal demand drops drone hardware prices after overstock.",
    techIds: ["drones"],
    budgetDelta: -1,
    willDelta: 0,
    icon: "🎁",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Drone delivery holiday rush. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/drone-delivery-holiday.jpg",
  },
  {
    id: "materials-breakthrough",
    headline: "Lab materials breakthrough",
    body: "A published process cuts specialty materials cost.",
    techIds: ["materials", "nano"],
    budgetDelta: -1,
    willDelta: 0,
    icon: "✨",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Lab materials breakthrough. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/materials-breakthrough.jpg",
  },
  {
    id: "quantum-error-milestone",
    headline: "Quantum error-correction milestone",
    body: "Hype returns with substance; quantum will eases, capital still high.",
    techIds: ["quantum"],
    budgetDelta: 0,
    willDelta: -1,
    icon: "⚛",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Quantum error-correction milestone. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/quantum-error-milestone.jpg",
  },
  {
    id: "network-neutrality-fight",
    headline: "Network neutrality fight",
    body: "ISPs and cities clash. Networks will cost rises.",
    techIds: ["networks"],
    budgetDelta: 0,
    willDelta: 1,
    icon: "⚖",
    tone: "bad",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Network neutrality fight. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/network-neutrality-fight.jpg",
  },
  {
    id: "fab-lab-franchise",
    headline: "Fab lab franchise wave",
    body: "Standardized print shops lower print3d startup capital.",
    techIds: ["print3d"],
    budgetDelta: -1,
    willDelta: 0,
    icon: "🏗",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Fab lab franchise wave. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/fab-lab-franchise.jpg",
  },
  {
    id: "robot-nurse-pilot",
    headline: "Robot nurse pilot praised",
    body: "Care outcomes soften political resistance to robots.",
    techIds: ["robots", "ai"],
    budgetDelta: 0,
    willDelta: -1,
    icon: "👩‍⚕️",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Robot nurse pilot praised. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/robot-nurse-pilot.jpg",
  },
  {
    id: "energy-poverty-fund",
    headline: "Energy poverty fund",
    body: "Targeted funds cut capital for solar, battery, and energy access stacks.",
    techIds: ["solar", "battery", "energy"],
    budgetDelta: -1,
    willDelta: 0,
    icon: "💡",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Energy poverty fund. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/energy-poverty-fund.jpg",
  },
  {
    id: "storm-rebuild-surge",
    headline: "Storm rebuild surge",
    body: "Demand spikes materials and drones; short-term capital rises.",
    techIds: ["materials", "drones", "print3d", "iot"],
    budgetDelta: 1,
    willDelta: 0,
    icon: "🏚",
    tone: "bad",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Storm rebuild surge. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/storm-rebuild-surge.jpg",
  },
  {
    id: "public-trust-rebound",
    headline: "Public trust rebound poll",
    body: "After quiet wins, will eases slightly across automator and mover tech.",
    domains: ["automator", "mover"],
    budgetDelta: 0,
    willDelta: -1,
    icon: "📊",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Public trust rebound poll. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/public-trust-rebound.jpg",
  },
  {
    id: "global-shipping-jam",
    headline: "Global shipping jam",
    body: "Hardware lead times stretch; power and portal budgets climb.",
    domains: ["power", "portal"],
    budgetDelta: 1,
    willDelta: 0,
    icon: "🚢",
    tone: "bad",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Global shipping jam. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/global-shipping-jam.jpg",
  },
  {
    id: "local-currency-pilot",
    headline: "Local currency and ledger pilot",
    body: "Municipal ledger pilots normalize crypto tooling.",
    techIds: ["crypto"],
    budgetDelta: 0,
    willDelta: -1,
    icon: "🪙",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Local currency and ledger pilot. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/local-currency-pilot.jpg",
  },
  {
    id: "ai-exam-cheating-panic",
    headline: "AI exam cheating panic",
    body: "Schools restrict AI; will cost rises for education-facing AI.",
    techIds: ["ai"],
    budgetDelta: 0,
    willDelta: 1,
    icon: "📝",
    tone: "bad",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: AI exam cheating panic. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/ai-exam-cheating-panic.jpg",
  },
  {
    id: "flood-sensor-rebate",
    headline: "Flood sensor rebate",
    body: "Water districts rebate IoT kits after a wet season.",
    techIds: ["iot", "networks"],
    budgetDelta: -1,
    willDelta: 0,
    icon: "💧",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Flood sensor rebate. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/flood-sensor-rebate.jpg",
  },
  {
    id: "heatwave-grid-alert",
    headline: "Heatwave grid alert",
    body: "Peak demand politics favor batteries and demand tech.",
    techIds: ["battery", "energy", "solar"],
    budgetDelta: 0,
    willDelta: -1,
    icon: "🌡",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Heatwave grid alert. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/heatwave-grid-alert.jpg",
  },
  {
    id: "venture-winter",
    headline: "Venture winter for deep tech",
    body: "Private capital flees long-horizon stacks; quantum and space budgets rise.",
    techIds: ["quantum", "space", "synbio"],
    budgetDelta: 1,
    willDelta: 0,
    icon: "🥶",
    tone: "bad",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Venture winter for deep tech. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/venture-winter.jpg",
  },
  {
    id: "co-op-procurement",
    headline: "Co-op multi-city procurement",
    body: "Cities bulk-buy sensors and panels together. Capital eases for IoT and solar.",
    techIds: ["iot", "solar", "battery"],
    budgetDelta: -1,
    willDelta: 0,
    icon: "🛒",
    tone: "good",
    imagePrompt: "Editorial news illustration for a strategy board game about emerging technology. Scene: Co-op multi-city procurement. Cinematic 16:9, rich color, no readable text, no logos, no watermarks.",
    image: "assets/market-news/co-op-procurement.jpg",
  },
];

/**
 * Does this market event apply to tech `t`?
 * @param {MarketNews|null|undefined} news
 * @param {{ id?: string, domain?: string }|null|undefined} tech
 */
export function marketAffectsTech(news, tech) {
  if (!news || !tech) return false;
  if (news.all) return true;
  const ids = news.techIds || [];
  if (ids.length && tech.id && ids.includes(tech.id)) return true;
  if (ids.length) return false; // techIds specified but no match
  const domains = news.domains || [];
  if (domains.length && tech.domain && domains.includes(tech.domain)) return true;
  return false;
}

/**
 * Apply market deltas to a base cost. Never changes AP. Floors at 0.
 * @param {{ budget: number, will: number, frontierRisk?: number }} base
 * @param {object|null|undefined} tech
 * @param {MarketNews|null|undefined} news
 */
export function applyMarketToCost(base, tech, news) {
  const out = {
    budget: Math.max(0, Number(base?.budget) || 0),
    will: Math.max(0, Number(base?.will) || 0),
    frontierRisk: Number(base?.frontierRisk) || 0,
  };
  if (!marketAffectsTech(news, tech)) return out;
  out.budget = Math.max(0, out.budget + (Number(news.budgetDelta) || 0));
  out.will = Math.max(0, out.will + (Number(news.willDelta) || 0));
  return out;
}

/**
 * Human-readable effect chips for UI.
 * @param {MarketNews|null|undefined} news
 * @param {{ techName?: (id: string) => string, domainLabel?: (d: string) => string }} [labels]
 * @returns {{ scope: string, effects: string[], tone: string }}
 */
export function describeMarketEffects(news, labels = {}) {
  if (!news) return { scope: "", effects: [], tone: "mixed" };
  const techName = labels.techName || ((id) => id);
  const domainLabel = labels.domainLabel || ((d) => d);
  let scope = "All emTechs";
  if (news.all) scope = "All emTechs";
  else if (news.techIds?.length) {
    scope = news.techIds.map(techName).join(", ");
  } else if (news.domains?.length) {
    scope = news.domains.map(domainLabel).join(" · ") + " domain";
  }
  const effects = [];
  const b = Number(news.budgetDelta) || 0;
  const w = Number(news.willDelta) || 0;
  if (b !== 0) effects.push(`Budget ${b > 0 ? "+" : ""}${b}$`);
  if (w !== 0) effects.push(`Will ${w > 0 ? "+" : ""}${w}`);
  if (!effects.length) effects.push("No cost change");
  return { scope, effects, tone: news.tone || "mixed" };
}

/**
 * Deterministic pick for a round. Avoids repeating the previous event when possible.
 * @param {object} [opts]
 * @param {string|number} [opts.seed]
 * @param {number} [opts.round]
 * @param {number} [opts.year]
 * @param {string|null} [opts.excludeId]
 * @param {MarketNews[]} [opts.pool]
 * @returns {MarketNews}
 */
export function pickMarketNews(opts = {}) {
  const pool = (opts.pool || MARKET_EVENTS).filter(Boolean);
  if (!pool.length) {
    return {
      id: "quiet-markets",
      headline: "Quiet markets",
      body: "No major shock this round — emTech prices hold.",
      all: true,
      budgetDelta: 0,
      willDelta: 0,
      icon: "📰",
      tone: "mixed",
      imagePrompt: "Editorial still life of a calm newspaper desk with soft morning light, 16:9, no text",
      round: opts.round ?? 1,
      year: opts.year,
    };
  }
  const seedStr = `${opts.seed ?? "market"}:r${opts.round ?? 1}:y${opts.year ?? 2026}`;
  const rng = mulberry32(hashSeed(seedStr));
  let candidates = pool;
  if (opts.excludeId && pool.length > 1) {
    const filtered = pool.filter((e) => e.id !== opts.excludeId);
    if (filtered.length) candidates = filtered;
  }
  const idx = Math.floor(rng() * candidates.length);
  const pick = candidates[Math.max(0, Math.min(idx, candidates.length - 1))];
  return {
    ...pick,
    budgetDelta: Number(pick.budgetDelta) || 0,
    willDelta: Number(pick.willDelta) || 0,
    techIds: pick.techIds ? [...pick.techIds] : undefined,
    domains: pick.domains ? [...pick.domains] : undefined,
    image: pick.image || (pick.id ? `assets/market-news/${pick.id}.jpg` : undefined),
    round: opts.round ?? 1,
    year: opts.year,
  };
}

/**
 * Roll a new market card for a completed round (solo turn / MP wrap).
 * @param {object} ctx
 * @param {number} ctx.round — round number this news applies to
 * @param {number} [ctx.year]
 * @param {string} [ctx.missionId]
 * @param {string|null} [ctx.prevId]
 * @returns {MarketNews}
 */
export function rollRoundMarketNews(ctx = {}) {
  return pickMarketNews({
    seed: `${ctx.missionId || "solo"}:${ctx.round || 1}`,
    round: ctx.round || 1,
    year: ctx.year,
    excludeId: ctx.prevId || null,
  });
}

/** Static path for a market card illustration (dev-time generated). */
export function marketNewsImagePath(news) {
  if (!news) return null;
  if (news.image) return news.image;
  if (news.id) return `assets/market-news/${news.id}.jpg`;
  return null;
}

/** Public JSON-safe clone */
export function cloneMarketNews(news) {
  if (!news) return null;
  return {
    id: news.id,
    headline: news.headline,
    body: news.body,
    techIds: news.techIds ? [...news.techIds] : undefined,
    domains: news.domains ? [...news.domains] : undefined,
    all: news.all || undefined,
    budgetDelta: Number(news.budgetDelta) || 0,
    willDelta: Number(news.willDelta) || 0,
    icon: news.icon || "📰",
    tone: news.tone || "mixed",
    imagePrompt: news.imagePrompt || "",
    image: news.image || (news.id ? `assets/market-news/${news.id}.jpg` : undefined),
    round: news.round,
    year: news.year,
  };
}
